### ISSUE TITLE
github.com/yashinu

### ISSUE THREAD

**Issue by SeonerVorteX** [thelaving/yulaf-snowouts-botlar#1]
Guard, Backup, Invite - Bu altyapıdaki kodların tamamı Yashinu'a aittir. Yulaf arkadaşına söyle hazır altyapıyı çalıp, milletin emeğine girerek bir şey elde etmeyecek

**Comment by thelaving** [comment]
Sen kimsin dostum yashinunun avukat'ı felanmı? Yashinu adlı arkadaş bu durumdan rahatsız olduysa yazsın bana çözelim aramızda seni burda kimse söz sahibi edemez. Kodlarda çalıntı felan banane ben insanlar faydalansın diye atıyorum.

**Comment by SeonerVorteX** [comment]
Benim kim olduğum kimseyi ilgilendirmez, ama sizin başkalarının altyapıları ile prim kasmaya çalışanlardan olduğunuz belli. Zaten githubda paylaşılmış bir altyapıyı hangi iq ile tekrar paylaşıp insanlara fayda sağlamaya çalıştığınızı merak ediyorum

**Comment by thelaving** [comment]
Kardeşim ben sanalı bile saldım ara sıra giriyorum neyin primini kasıcam? 1 Yıl önce paylaşılan botu alan almıştı şimdi herkes alabilir az zekanı kullan
